name: playx_3d_scene
description: Plugin for showing 3d models in flutter.
version: 0.0.4

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.sourcya.playx_3d_scene
        pluginClass: Playx3dScenePlugin



