name: playx_3d_scene
description: Plugin for rendering interactive 3D models based on Google filament natively on Android. 
  With the ability of controlling environment skybox, light, camera, ground and more.
version: 0.0.2
homepage: https://sourcya.com/
repository: https://github.com/playx-flutter/playx-3d-scene
issue_tracker: https://github.com/playx-flutter/playx-3d-scene/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.sourcya.playx_3d_scene
        pluginClass: Playx3dScenePlugin



